### ISSUE TITLE
mirage-nat doesn't install with latest mirage tool (3.7.2)

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-nat#35]
The current version of `mirage` (3.7.2) depends on `"mirage-clock-freestanding" { >= "3.0.0" & < "4.0.0"}`, which depends on `mirage-clock` with the same version (i.e. at least 3).

However, the current `mirage-nat` (1.2.0) depends on `mirage-clock-lwt`, which I think is now obsolete and depends on `mirage-clock < 3`.

Is this repository ready for a new release?

**Comment by hannesm** [comment]
#34 adjusted the mirage-nat library to a current mirage. I intended to wait for a release until I managed to rebase and PR my IPv4 fragmentation and reassembly fixes (see https://github.com/mirage/qubes-mirage-firewall/issues/73 for further discussion).
In addition I'd be in favour to merge #33, please let me know what you think. If you have more pressing issues, don't hesitate to create a release with the current master state.

**Comment by talex5** [comment]
It's not urgent: I just tried updating mirage-firewall's Dockerfile to use the latest mirage and noticed that it didn't work.

**Comment by hannesm** [comment]
PRed mirage-nat 2.0.0 as https://github.com/ocaml/opam-repository/pull/15572, thanks for your patience :)
